# Generated by Django 5.0.7 on 2026-08-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_muestraco2_unidad_muestreo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAutollenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=80, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('modelo_destino', models.CharField(max_length=100, verbose_name='modelo destino')),
                ('campo_destino', models.CharField(max_length=100, verbose_name='campo destino')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'regla de autollenado',
                'verbose_name_plural': 'reglas de autollenado',
                'ordering': ['modelo_destino', 'campo_destino'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objeto_id', models.PositiveIntegerField(verbose_name='id del objeto')),
                ('valor_anterior', models.CharField(blank=True, default='', max_length=500, verbose_name='valor anterior')),
                ('valor_nuevo', models.CharField(max_length=500, verbose_name='valor nuevo')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='app.reglaautollenado', verbose_name='regla')),
            ],
            options={
                'verbose_name': 'aplicación de regla',
                'verbose_name_plural': 'aplicaciones de reglas',
                'ordering': ['-created_at'],
            },
        ),
    ]
