# Generated by Django 5.0.7 on 2026-08-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_reglaautollenado_aplicacionregla'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglaautollenado',
            name='parametros',
            field=models.JSONField(blank=True, default=dict, help_text='Valores que ajustan el cálculo de la regla (ver parametros_default en el registro Python). Si una clave no está aquí, se usa el valor por defecto del código.', verbose_name='parámetros'),
        ),
    ]
