# Generated by Django 5.0.7 on 2026-08-03 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_reglaautollenado_parametros'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionregla',
            name='deshecha_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deshecha en'),
        ),
        migrations.AddField(
            model_name='aplicacionregla',
            name='lote',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='lote'),
        ),
        migrations.AddIndex(
            model_name='aplicacionregla',
            index=models.Index(fields=['lote'], name='app_aplicac_lote_c2ec76_idx'),
        ),
    ]
