# Generated by Django 5.0.7 on 2026-08-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_aplicacionregla_deshecha_en_aplicacionregla_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestraambiental',
            name='unidad_muestreo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muestras_ambientales', to='app.unidadmuestreo', verbose_name='unidad de muestreo'),
        ),
    ]
