# Generated by Django 5.0.7 on 2026-08-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_muestraambiental_unidad_muestreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestraambiental',
            name='momento',
            field=models.CharField(blank=True, choices=[('inicio', 'Inicio'), ('final', 'Final')], max_length=10, verbose_name='momento'),
        ),
    ]
