# Generated by Django 5.0.7 on 2026-08-04 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_muestraambiental_momento'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadexperimental',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_experimentales', to='app.unidadmuestreotipo', verbose_name='tipo'),
        ),
    ]
