# Generated by Django 5.0.7 on 2026-08-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_unidadexperimental_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='diametro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='diámetro (m)'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='distancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='distancia / lado (m)'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='forma',
            field=models.CharField(blank=True, choices=[('Cuadrada', 'Cuadrada'), ('Rectangular', 'Rectangular'), ('Circular', 'Circular')], max_length=15, verbose_name='forma'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='área (m²)'),
        ),
    ]
