# Generated by Django 5.0.7 on 2026-08-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_parcela_diametro_parcela_distancia_parcela_forma_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapeocolumna',
            unique_together={('carga', 'columna_origen', 'modelo_destino', 'campo_destino')},
        ),
        migrations.AddField(
            model_name='mapeocolumna',
            name='regex_patron',
            field=models.CharField(blank=True, default='', help_text="Expresión regular aplicada al valor de origen cuando la transformación es 'regex'. Si tiene un grupo de captura se usa ese grupo; si no, se usa la coincidencia completa. Sin coincidencia, el valor queda vacío. Ej: '^SWAMP_CO2_(.+?)_\\d+$' sobre 'SWAMP_CO2_S1_old_3' da 'S1_old'.", max_length=255, verbose_name='patrón regex'),
        ),
        migrations.AlterField(
            model_name='mapeocolumna',
            name='transformacion',
            field=models.CharField(choices=[('directo', 'Directo'), ('lookup', 'Lookup / FK'), ('split', 'Split'), ('fecha', 'Parsear fecha'), ('regex', 'Expresión regular'), ('constante', 'Valor constante'), ('ignorar', 'Ignorar')], default='directo', max_length=20, verbose_name='transformación'),
        ),
    ]
