# Generated by Django 5.0.7 on 2026-08-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_mapeocolumna_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmuestreo',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha instalación unidad de muestreo'),
        ),
    ]
