# Generated by Django 5.0.7 on 2026-08-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_unidadmuestreo_fecha_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestraambiental',
            name='microtopo',
            field=models.CharField(blank=True, choices=[('Hummock', 'Hummock (cojines)'), ('Hollow', 'Hollow (depresiones húmedas)'), ('Pool', 'Pool (charcos / sobre agua)'), ('Lawns', 'Lawns (lugares planos)')], max_length=10, verbose_name='microtopología (microtopography)'),
        ),
    ]
