# Generated by Django 5.0.7 on 2026-08-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_muestraambiental_microtopo_ditch'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestraambiental',
            name='water_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='nivel del agua (cm)'),
        ),
    ]
