# Generated by Django 5.0.7 on 2026-08-06 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_muestraambiental_unidad_muestreo_requerida'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestraambiental',
            name='fuente_datos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_ambientales', to='app.fuentedatos', verbose_name='fuente de datos'),
        ),
        migrations.AddConstraint(
            model_name='muestraambiental',
            constraint=models.UniqueConstraint(fields=('fecha', 'hora', 'fuente_datos'), name='muestra_ambiental_unica_por_fecha_hora_fuente'),
        ),
    ]
