# Generated by Django 5.0.7 on 2026-08-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_muestraambiental_fuente_datos_unica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muestraco2',
            old_name='camara',
            new_name='analizador',
        ),
        migrations.RemoveIndex(
            model_name='muestraco2',
            name='app_muestra_camara__96dce6_idx',
        ),
        migrations.AddIndex(
            model_name='muestraco2',
            index=models.Index(fields=['analizador'], name='app_muestra_analiza_04b67d_idx'),
        ),
    ]
