# Generated by Django 5.0.7 on 2026-08-10 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_rename_camara_to_analizador_muestraco2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestraco2',
            name='analizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muestras_co2', to='app.camara', verbose_name='analizador'),
        ),
    ]
