# Generated by Django 5.0.7 on 2026-08-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_muestraco2_analizador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muestraco2',
            old_name='anillo',
            new_name='tubo',
        ),
        migrations.RemoveIndex(
            model_name='muestraco2',
            name='app_muestra_anillo__4f7987_idx',
        ),
        migrations.AddIndex(
            model_name='muestraco2',
            index=models.Index(fields=['tubo'], name='app_muestra_tubo_id_2ed455_idx'),
        ),
    ]
