# Generated by Django 5.0.7 on 2026-08-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_rename_anillo_to_tubo_muestraco2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestraco2',
            name='tubo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muestras_co2', to='app.anillo', verbose_name='tubo'),
        ),
    ]
