# Generated by Django 5.0.7 on 2026-08-10 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_muestraco2_tubo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['modelo'], 'verbose_name': 'equipo', 'verbose_name_plural': 'equipos'},
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='tipo_equipo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='torre',
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='descripción'),
        ),
        migrations.CreateModel(
            name='TipoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gas', models.CharField(choices=[('CO2', 'CO₂'), ('CH4', 'CH₄'), ('N2O', 'N₂O')], max_length=4, verbose_name='gas')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_muestra', to='app.equipo', verbose_name='equipo')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_muestra', to='app.unidadmedida', verbose_name='unidad de medida')),
            ],
            options={
                'verbose_name': 'tipo de muestra',
                'verbose_name_plural': 'tipos de muestra',
                'ordering': ['equipo', 'gas'],
                'unique_together': {('equipo', 'gas')},
            },
        ),
    ]
