# Generated by Django 5.0.7 on 2026-08-10 21:20

from django.db import migrations


UNIDADES = {
    "g_m2_h": ("gramos por metro cuadrado por hora", "flujo"),
    "umol_m2_s": ("micromoles por metro cuadrado por segundo", "flujo"),
    "nmol_m2_s": ("nanomoles por metro cuadrado por segundo", "flujo"),
}

EQUIPOS = {
    "EGM-4": [("CO2", "g_m2_h")],
    "EGM-5": [("CO2", "g_m2_h")],
    "Picarro G4301": [("CH4", "umol_m2_s"), ("CO2", "umol_m2_s")],
    "Licor 7810": [("CH4", "nmol_m2_s"), ("CO2", "umol_m2_s")],
}


def seed(apps, schema_editor):
    UnidadMedida = apps.get_model("app", "UnidadMedida")
    Equipo = apps.get_model("app", "Equipo")
    TipoMuestra = apps.get_model("app", "TipoMuestra")

    unidades = {}
    for codigo, (descripcion, magnitud) in UNIDADES.items():
        obj, _ = UnidadMedida.objects.get_or_create(
            codigo=codigo, defaults={"descripcion": descripcion, "magnitud": magnitud},
        )
        unidades[codigo] = obj

    for modelo, gases in EQUIPOS.items():
        equipo, _ = Equipo.objects.get_or_create(modelo=modelo)
        for gas, codigo_unidad in gases:
            TipoMuestra.objects.get_or_create(
                equipo=equipo, gas=gas, defaults={"unidad_medida": unidades[codigo_unidad]},
            )


def unseed(apps, schema_editor):
    Equipo = apps.get_model("app", "Equipo")
    UnidadMedida = apps.get_model("app", "UnidadMedida")

    Equipo.objects.filter(modelo__in=EQUIPOS.keys()).delete()
    UnidadMedida.objects.filter(codigo__in=UNIDADES.keys()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_equipo_options_remove_equipo_tipo_equipo_and_more'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
