# Generated by Django 5.0.7 on 2026-08-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_seed_unidades_medida_equipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submuestraco2',
            name='unidad_medida',
        ),
    ]
