# Generated by Django 5.0.7 on 2026-08-10 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_submuestraco2_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestraco2',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muestras_co2', to='app.unidadmedida', verbose_name='unidad de medida'),
        ),
    ]
