# Generated by Django 5.0.7 on 2026-08-10 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_muestraco2_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestraco2',
            name='analizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='muestras_co2', to='app.equipo', verbose_name='analizador'),
        ),
        migrations.DeleteModel(
            name='Camara',
        ),
    ]
