# Generated by Django 5.0.7 on 2026-08-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_muestraco2_analizador_delete_camara'),
    ]

    operations = [
        migrations.AddField(
            model_name='submuestraco2',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de la toma'),
        ),
    ]
