# Generated by Django 5.0.7 on 2026-08-10 22:00

from django.db import migrations


def copiar_fecha(apps, schema_editor):
    SubmuestraCO2 = apps.get_model("app", "SubmuestraCO2")
    submuestras = SubmuestraCO2.objects.filter(fecha=None).select_related("muestra")
    actualizadas = []
    for sub in submuestras:
        if sub.muestra.fecha is not None:
            sub.fecha = sub.muestra.fecha
            actualizadas.append(sub)
    SubmuestraCO2.objects.bulk_update(actualizadas, ["fecha"], batch_size=500)


def revertir(apps, schema_editor):
    # No hay forma de distinguir la fecha copiada de una fecha propia
    # cargada después, así que no se deshace nada.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_submuestraco2_fecha'),
    ]

    operations = [
        migrations.RunPython(copiar_fecha, revertir),
    ]
