# Generated by Django 5.0.7 on 2026-08-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_copiar_fecha_muestra_a_submuestra'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='muestraco2',
            name='app_muestra_tubo_id_2ed455_idx',
        ),
        migrations.RemoveField(
            model_name='muestraco2',
            name='tubo',
        ),
        migrations.RemoveField(
            model_name='muestraco2',
            name='muestra_ambiental',
        ),
        migrations.RemoveField(
            model_name='muestraco2',
            name='fecha',
        ),
        migrations.AddField(
            model_name='muestraco2',
            name='tubo',
            field=models.CharField(blank=True, max_length=80, verbose_name='tubo'),
        ),
        migrations.AlterModelOptions(
            name='muestraco2',
            options={'ordering': ['-created_at'], 'verbose_name': 'muestra CO₂', 'verbose_name_plural': 'muestras CO₂'},
        ),
        migrations.DeleteModel(
            name='Anillo',
        ),
    ]
