# Generated by Django 5.0.7 on 2026-08-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_muestraco2_simplify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmuestreo',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255, verbose_name='nombre'),
        ),
    ]
