# Generated by Django 5.0.7 on 2026-08-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_unidadmuestreo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestraco2',
            name='gas',
            field=models.CharField(blank=True, choices=[('CO2', 'CO₂'), ('CH4', 'CH₄'), ('N2O', 'N₂O')], max_length=4, verbose_name='gas'),
        ),
    ]
