# Generated by Django 5.0.7 on 2026-08-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_backfill_muestraco2_gas_co2'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='geom',
            field=models.JSONField(blank=True, null=True, verbose_name='geometría (GeoJSON)'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(choices=[('Amazonas', 'Amazonas'), ('Antioquia', 'Antioquia'), ('Arauca', 'Arauca'), ('Atlantico', 'Atlántico'), ('Bogota_DC', 'Bogotá, D.C.'), ('Bolivar', 'Bolívar'), ('Boyaca', 'Boyacá'), ('Caldas', 'Caldas'), ('Caqueta', 'Caquetá'), ('Casanare', 'Casanare'), ('Cauca', 'Cauca'), ('Cesar', 'Cesar'), ('Choco', 'Chocó'), ('Cordoba', 'Córdoba'), ('Cundinamarca', 'Cundinamarca'), ('Guainia', 'Guainía'), ('Guaviare', 'Guaviare'), ('Huila', 'Huila'), ('La_Guajira', 'La Guajira'), ('Magdalena', 'Magdalena'), ('Meta', 'Meta'), ('Narinio', 'Nariño'), ('Norte_de_Santander', 'Norte de Santander'), ('Putumayo', 'Putumayo'), ('Quindio', 'Quindío'), ('Risaralda', 'Risaralda'), ('San_Andres', 'San Andrés, Providencia y Santa Catalina'), ('Santander', 'Santander'), ('Sucre', 'Sucre'), ('Tolima', 'Tolima'), ('Valle_del_Cauca', 'Valle del Cauca'), ('Vaupes', 'Vaupés'), ('Vichada', 'Vichada')], max_length=40, unique=True),
        ),
    ]
