# Generated by Django 5.0.7 on 2026-08-18 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_vereda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitio',
            name='municipio',
        ),
        migrations.AddField(
            model_name='sitio',
            name='vereda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sitios', to='app.vereda'),
        ),
    ]
