# Generated by Django 5.0.7 on 2026-08-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_remove_sitio_municipio_sitio_vereda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Notas adicionales sobre el equipo.', max_length=255, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo del equipo analizador (ej. Picarro G4301, LI-7810).', max_length=120, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(blank=True, help_text='Número de serie del equipo, para identificar el instrumento físico usado.', max_length=120, verbose_name='serial'),
        ),
        migrations.AlterField(
            model_name='muestraambiental',
            name='air_temp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura del aire, en grados Celsius.', max_digits=6, null=True, verbose_name='temperatura del aire (°C)'),
        ),
        migrations.AlterField(
            model_name='muestraambiental',
            name='atm_press',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Presión atmosférica, en hectopascales (hPa).', max_digits=8, null=True, verbose_name='presión atmosférica (hPa)'),
        ),
        migrations.AlterField(
            model_name='muestraambiental',
            name='dew_point',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Punto de rocío, en grados Celsius.', max_digits=6, null=True, verbose_name='punto de rocío (°C)'),
        ),
        migrations.AlterField(
            model_name='muestraambiental',
            name='fecha',
            field=models.DateField(blank=True, help_text='Fecha de la lectura ambiental.', null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='muestraambiental',
            name='hora',
            field=models.TimeField(blank=True, help_text='Hora de la lectura ambiental.', null=True, verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='muestraambiental',
            name='microtopo',
            field=models.CharField(blank=True, choices=[('Hummock', 'Hummock (cojines)'), ('Hollow', 'Hollow (depresiones húmedas)'), ('Pool', 'Pool (charcos / sobre agua)'), ('Lawns', 'Lawns (lugares planos)'), ('Ditch', 'Ditch (zanja / canal)')], help_text='Microtopografía del punto de medición.', max_length=10, verbose_name='microtopología (microtopography)'),
        ),
        migrations.AlterField(
            model_name='muestraambiental',
            name='momento',
            field=models.CharField(blank=True, choices=[('inicio', 'Inicio'), ('final', 'Final')], help_text='Si la lectura corresponde al inicio o al final de la medición, cuando la fuente reporta un rango en vez de un único valor.', max_length=10, verbose_name='momento'),
        ),
        migrations.AlterField(
            model_name='muestraambiental',
            name='relat_humid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Humedad relativa del aire, en porcentaje.', max_digits=5, null=True, verbose_name='humedad relativa (%)'),
        ),
        migrations.AlterField(
            model_name='muestraambiental',
            name='soil_temp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura del suelo, en grados Celsius.', max_digits=6, null=True, verbose_name='temperatura del suelo (°C)'),
        ),
        migrations.AlterField(
            model_name='muestraambiental',
            name='water_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nivel del agua respecto a la superficie, en centímetros: positivo indica encharcamiento, negativo indica nivel freático por debajo de la superficie.', max_digits=6, null=True, verbose_name='nivel del agua (cm)'),
        ),
        migrations.AlterField(
            model_name='muestragei',
            name='gas',
            field=models.CharField(blank=True, choices=[('CO2', 'CO₂'), ('CH4', 'CH₄'), ('N2O', 'N₂O')], help_text='Gas medido en esta muestra: CO₂, CH₄ o N₂O.', max_length=4, verbose_name='gas'),
        ),
        migrations.AlterField(
            model_name='muestragei',
            name='tubo',
            field=models.CharField(blank=True, help_text='Identificador del tubo/cámara conectado al equipo para esta medición.', max_length=80, verbose_name='tubo'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='altitud',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altitud del sitio sobre el nivel del mar, en metros.', max_digits=8, null=True, verbose_name='altitud (m.s.n.m.)'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='codigo_metadatos',
            field=models.CharField(blank=True, help_text='Código del sitio en el sistema de metadatos externo, si aplica.', max_length=80, verbose_name='código de metadatos'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='intervenido',
            field=models.BooleanField(default=False, help_text='Si el sitio ha sido intervenido/alterado por actividad humana.', verbose_name='intervenido'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='latitud',
            field=models.DecimalField(decimal_places=7, help_text='Latitud del sitio en grados decimales (WGS84). Fuente de verdad editable; de aquí se deriva la geometría del punto (geom).', max_digits=10, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='longitud',
            field=models.DecimalField(decimal_places=7, help_text='Longitud del sitio en grados decimales (WGS84). Fuente de verdad editable; de aquí se deriva la geometría del punto (geom).', max_digits=10, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='nombre',
            field=models.CharField(help_text='Nombre del sitio de estudio.', max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='pendiente',
            field=models.CharField(blank=True, choices=[('plano', 'Plano'), ('ondulado_variable', 'Ondulado / variable'), ('valle_fondo', 'Valle / fondo'), ('pendiente_suave', 'Pendiente suave (<2%)'), ('pendiente_media', 'Pendiente media (2–5%)'), ('pendiente_significativa', 'Pendiente significativa (5–10%)'), ('pendiente_fuerte', 'Pendiente fuerte (>10%)'), ('cresta_cima', 'Cresta / cima')], help_text='Categoría de pendiente del terreno en el sitio.', max_length=30, verbose_name='pendiente'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='propiedad_tierra',
            field=models.CharField(blank=True, choices=[('publica', 'Pública'), ('privada', 'Privada')], help_text='Si la tierra del sitio es de propiedad pública o privada.', max_length=10, verbose_name='propiedad de la tierra'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='topografia',
            field=models.CharField(blank=True, choices=[('cresta_cima', 'Cresta / cima'), ('ladera_superior', 'Ladera superior'), ('ladera_media', 'Ladera media'), ('ladera_inferior', 'Ladera inferior'), ('valle_fondo', 'Valle / fondo'), ('plano', 'Plano')], help_text='Posición topográfica del sitio (cresta, ladera, valle, etc.).', max_length=24, verbose_name='topografía'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='uso_actual',
            field=models.CharField(blank=True, choices=[('Bosque_primario', 'Bosque primario'), ('Bosque_secundario', 'Bosque secundario'), ('Plantacion_forestal', 'Plantación forestal'), ('Agricultura_intensiva', 'Agricultura intensiva'), ('Agricultura_tradicional', 'Agricultura tradicional'), ('Pastura', 'Pastura'), ('Humedal_natural', 'Humedal natural'), ('Humedal_intervenido', 'Humedal intervenido'), ('Area_protegida', 'Área protegida'), ('Sistema_agroforestal', 'Sistema agroforestal'), ('Abandonado', 'Abandonado'), ('Restauracion_activa', 'Restauración activa')], help_text='Uso actual del suelo en el sitio.', max_length=30, verbose_name='uso actual del suelo'),
        ),
        migrations.AlterField(
            model_name='submuestragei',
            name='condicion_luz',
            field=models.CharField(blank=True, choices=[('dia', 'Día'), ('noche', 'Noche'), ('noche_simulada', 'Noche simulada (cobija)')], help_text='Condición de luz bajo la que se tomó la muestra.', max_length=15, verbose_name='condición de luz'),
        ),
        migrations.AlterField(
            model_name='submuestragei',
            name='fecha',
            field=models.DateField(blank=True, help_text='Fecha en la que se realizó esta toma.', null=True, verbose_name='fecha de la toma'),
        ),
        migrations.AlterField(
            model_name='submuestragei',
            name='hora',
            field=models.TimeField(blank=True, help_text='Hora en la que se realizó esta toma.', null=True, verbose_name='hora de la toma'),
        ),
        migrations.AlterField(
            model_name='submuestragei',
            name='momento',
            field=models.CharField(blank=True, choices=[('inicio', 'Inicio'), ('final', 'Final')], help_text='Si la toma corresponde al inicio o al final de la medición.', max_length=10, verbose_name='momento'),
        ),
        migrations.AlterField(
            model_name='submuestragei',
            name='n_toma',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de orden de la toma dentro de la muestra (ej. 1 de ~4 tomas sucesivas).', null=True, verbose_name='número de toma'),
        ),
        migrations.AlterField(
            model_name='submuestragei',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Valor medido del flujo de gas, en la unidad reportada por la muestra (MuestraGEI.unidad_medida).', max_digits=14, null=True, verbose_name='valor del flujo'),
        ),
        migrations.AlterField(
            model_name='unidadexperimental',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la unidad experimental.', verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='unidadexperimental',
            name='nombre',
            field=models.CharField(help_text='Nombre de la unidad experimental (agrupa las unidades de muestreo que reciben el mismo tratamiento).', max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='codigo',
            field=models.CharField(help_text='Código corto de la unidad de medida (ej. co2_flux_micromol_m2_s).', max_length=80, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción legible de la unidad de medida.', max_length=255, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='unidadmuestreo',
            name='fecha_instalacion',
            field=models.DateField(blank=True, help_text='Fecha en la que se instaló o estableció la unidad de muestreo en campo.', null=True, verbose_name='fecha instalación unidad de muestreo'),
        ),
        migrations.AlterField(
            model_name='unidadmuestreo',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Identificador de la unidad de muestreo tal como lo reporta la fuente (ej. el número o código de la parcela/punto).', max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='unidadmuestreotipo',
            name='nombre',
            field=models.CharField(help_text='Nombre del tipo de unidad de muestreo (ej. parcela, transecto, conglomerado, plot).', max_length=80, unique=True, verbose_name='nombre'),
        ),
    ]
