# Generated by Django 5.0.7 on 2026-08-28 15:13

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_help_text_diccionario_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroChatIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origen', models.CharField(choices=[('web', 'Panel web'), ('telegram', 'Telegram'), ('api', 'API directa')], default='api', max_length=20)),
                ('usuario_externo_id', models.CharField(blank=True, help_text='Identificador del usuario en el canal de origen (p. ej. chat_id de Telegram).', max_length=120)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField(blank=True)),
                ('herramienta_usada', models.CharField(blank=True, max_length=60)),
                ('datos_pendientes_confirmar', models.JSONField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'registro de chat IA',
                'verbose_name_plural': 'registros de chat IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('entrevista', 'Entrevista transcrita'), ('diccionario', 'Diccionario de terminos'), ('informe', 'Informe o documento tecnico'), ('nota_campo', 'Nota de campo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('texto_completo', models.TextField(blank=True, help_text='Contenido crudo. Para entrevistas, la transcripcion completa.')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=180)),
                ('archivo_origen', models.CharField(blank=True, max_length=255)),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('procesado', models.BooleanField(default=False, help_text='True cuando ya se generaron sus fragmentos y embeddings.')),
                ('sitio', models.ForeignKey(blank=True, help_text='Sitio al que se refiere el documento, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_conocimiento', to='app.sitio')),
            ],
            options={
                'verbose_name': 'documento de conocimiento',
                'verbose_name_plural': 'documentos de conocimiento',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicionRapidaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('variable', models.CharField(choices=[('CO2', 'Flujo de CO2'), ('CH4', 'Flujo de CH4'), ('N2O', 'Flujo de N2O'), ('temperatura_aire', 'Temperatura del aire'), ('temperatura_suelo', 'Temperatura del suelo'), ('humedad_relativa', 'Humedad relativa'), ('nivel_agua', 'Nivel del agua'), ('otro', 'Otra variable')], max_length=30)),
                ('variable_otro', models.CharField(blank=True, help_text="Si 'variable' es 'otro', el nombre real.", max_length=120)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad', models.CharField(blank=True, max_length=30)),
                ('observacion_texto', models.TextField(help_text='El mensaje original tal como lo escribio la persona.')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones_rapidas_chat', to='app.sitio')),
                ('registro_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_generadas', to='app.registrochatia')),
            ],
            options={
                'verbose_name': 'medicion rapida (chat IA)',
                'verbose_name_plural': 'mediciones rapidas (chat IA)',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TerminoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(blank=True, help_text='P. ej. Olor, Color, Suelo al pisar/tocar.', max_length=60)),
                ('observacion_campo', models.CharField(max_length=255)),
                ('definicion_ecologica', models.TextField(blank=True)),
                ('variable_asociada', models.CharField(blank=True, max_length=120)),
                ('variable_secundaria', models.CharField(blank=True, max_length=255)),
                ('regla_cuantitativa', models.TextField(blank=True)),
                ('interpretacion', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('origen', models.CharField(choices=[('manual', 'Cargado o editado a mano'), ('excel', 'Importado del Excel del diccionario'), ('extraido_ia', 'Propuesto por la IA desde un documento')], default='excel', max_length=20)),
                ('confirmado', models.BooleanField(default=True, help_text='False mientras sea una propuesta de la IA sin validar.')),
                ('documento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminos_extraidos', to='app.documentoconocimiento')),
            ],
            options={
                'verbose_name': 'termino de campo',
                'verbose_name_plural': 'terminos de campo',
                'ordering': ['categoria', 'observacion_campo'],
            },
        ),
        migrations.CreateModel(
            name='FragmentoConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('texto', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='app.documentoconocimiento')),
            ],
            options={
                'verbose_name': 'fragmento de conocimiento',
                'verbose_name_plural': 'fragmentos de conocimiento',
                'ordering': ['documento_id', 'orden'],
                'unique_together': {('documento', 'orden')},
            },
        ),
    ]
